"""init schema

Revision ID: 1c69967a4374
Revises: 
Create Date: 2026-01-12 12:14:24.550619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c69967a4374'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name_official', sa.String(length=255), nullable=False),
    sa.Column('name_aliases', sa.Text(), nullable=True),
    sa.Column('supplier_org', sa.String(length=255), nullable=True),
    sa.Column('supplier_type', sa.String(length=50), nullable=True),
    sa.Column('supplier_other', sa.String(length=255), nullable=True),
    sa.Column('category_main', sa.String(length=100), nullable=False),
    sa.Column('category_other', sa.String(length=255), nullable=True),
    sa.Column('material_forms', sa.Text(), nullable=True),
    sa.Column('material_forms_other', sa.String(length=255), nullable=True),
    sa.Column('origin_type', sa.String(length=50), nullable=False),
    sa.Column('origin_detail', sa.String(length=255), nullable=False),
    sa.Column('origin_other', sa.String(length=255), nullable=True),
    sa.Column('recycle_bio_rate', sa.Float(), nullable=True),
    sa.Column('recycle_bio_basis', sa.String(length=50), nullable=True),
    sa.Column('color_tags', sa.Text(), nullable=True),
    sa.Column('transparency', sa.String(length=50), nullable=False),
    sa.Column('hardness_qualitative', sa.String(length=50), nullable=False),
    sa.Column('hardness_value', sa.String(length=100), nullable=True),
    sa.Column('weight_qualitative', sa.String(length=50), nullable=False),
    sa.Column('specific_gravity', sa.Float(), nullable=True),
    sa.Column('water_resistance', sa.String(length=50), nullable=False),
    sa.Column('heat_resistance_temp', sa.Float(), nullable=True),
    sa.Column('heat_resistance_range', sa.String(length=50), nullable=False),
    sa.Column('weather_resistance', sa.String(length=50), nullable=False),
    sa.Column('processing_methods', sa.Text(), nullable=True),
    sa.Column('processing_other', sa.String(length=255), nullable=True),
    sa.Column('equipment_level', sa.String(length=50), server_default='家庭/工房レベル', nullable=False),
    sa.Column('prototyping_difficulty', sa.String(length=50), server_default='中', nullable=False),
    sa.Column('use_categories', sa.Text(), nullable=True),
    sa.Column('use_other', sa.String(length=255), nullable=True),
    sa.Column('procurement_status', sa.String(length=50), nullable=False),
    sa.Column('cost_level', sa.String(length=50), nullable=False),
    sa.Column('cost_value', sa.Float(), nullable=True),
    sa.Column('cost_unit', sa.String(length=50), nullable=True),
    sa.Column('safety_tags', sa.Text(), nullable=True),
    sa.Column('safety_other', sa.String(length=255), nullable=True),
    sa.Column('restrictions', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('is_published', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('development_motives', sa.Text(), nullable=True),
    sa.Column('development_motive_other', sa.String(length=255), nullable=True),
    sa.Column('development_background_short', sa.String(length=500), nullable=True),
    sa.Column('development_story', sa.Text(), nullable=True),
    sa.Column('related_materials', sa.Text(), nullable=True),
    sa.Column('tactile_tags', sa.Text(), nullable=True),
    sa.Column('tactile_other', sa.String(length=255), nullable=True),
    sa.Column('visual_tags', sa.Text(), nullable=True),
    sa.Column('visual_other', sa.String(length=255), nullable=True),
    sa.Column('sound_smell', sa.String(length=500), nullable=True),
    sa.Column('ng_uses', sa.Text(), nullable=True),
    sa.Column('ng_uses_detail', sa.Text(), nullable=True),
    sa.Column('rejected_uses', sa.Text(), nullable=True),
    sa.Column('suitable_shapes', sa.Text(), nullable=True),
    sa.Column('suitable_shapes_other', sa.String(length=255), nullable=True),
    sa.Column('compatible_materials', sa.Text(), nullable=True),
    sa.Column('processing_knowhow', sa.Text(), nullable=True),
    sa.Column('circularity', sa.String(length=50), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('certifications_other', sa.String(length=255), nullable=True),
    sa.Column('question_templates', sa.Text(), nullable=True),
    sa.Column('question_answers', sa.Text(), nullable=True),
    sa.Column('main_elements', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('texture_image_path', sa.String(length=500), nullable=True),
    sa.Column('texture_image_url', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_category'), 'materials', ['category'], unique=False)
    op.create_index(op.f('ix_materials_category_main'), 'materials', ['category_main'], unique=False)
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_name_official'), 'materials', ['name_official'], unique=False)
    op.create_index(op.f('ix_materials_uuid'), 'materials', ['uuid'], unique=True)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('material_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'key', name='uq_metadata_material_key')
    )
    op.create_index(op.f('ix_material_metadata_id'), 'material_metadata', ['id'], unique=False)
    op.create_table('material_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('editor_note', sa.Text(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('approved_material_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_submissions_id'), 'material_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_material_submissions_uuid'), 'material_submissions', ['uuid'], unique=True)
    op.create_table('process_example_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('process_method', sa.String(length=100), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('license_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_example_images_id'), 'process_example_images', ['id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('measurement_condition', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'property_name', name='uq_property_material_name')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_table('reference_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('url_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_urls_id'), 'reference_urls', ['id'], unique=False)
    op.create_table('use_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('example_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('license_note', sa.Text(), nullable=True),
    sa.Column('example_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'example_name', name='uq_use_example_material_name')
    )
    op.create_index(op.f('ix_use_examples_id'), 'use_examples', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_use_examples_id'), table_name='use_examples')
    op.drop_table('use_examples')
    op.drop_index(op.f('ix_reference_urls_id'), table_name='reference_urls')
    op.drop_table('reference_urls')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_process_example_images_id'), table_name='process_example_images')
    op.drop_table('process_example_images')
    op.drop_index(op.f('ix_material_submissions_uuid'), table_name='material_submissions')
    op.drop_index(op.f('ix_material_submissions_id'), table_name='material_submissions')
    op.drop_table('material_submissions')
    op.drop_index(op.f('ix_material_metadata_id'), table_name='material_metadata')
    op.drop_table('material_metadata')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_materials_uuid'), table_name='materials')
    op.drop_index(op.f('ix_materials_name_official'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_category_main'), table_name='materials')
    op.drop_index(op.f('ix_materials_category'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###
